name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd /home/tiago/projects/services/estudaqui
            ./install-and-restart.sh

#todo check if server is up
      - name: Check server status
        run: |
          pause 5
          if ! curl -s --head http://37.27.208.65:3000 | grep "200 OK" > /dev/null; then
            echo "Server is not running!"
            exit 1
          else
            echo "Server is running successfully."
          fi