name: Deploy Firebase Functions

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy-functions:
    name: Deploy Firebase Functions
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        
      - name: Install Python dependencies
        run: |
          cd functions
          pip install -r requirements.txt
          
      - name: Check for syntax errors
        run: |
          cd functions
          python -m compileall .
          
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions --project estudaqui
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          
      - name: Notify on success
        if: success()
        run: echo "✅ Functions deployed successfully!"
        
      - name: Notify on failure
        if: failure()
        run: echo "❌ Function deployment failed!"
