name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies 
        run: |
          cd frontend
          bun install

      - name: Build the project
        run: |
          bun run build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd /home/tiago/projects/services/estudaqui
            ./install-and-restart.sh
      - name: Check server status
        run: |
          sleep 5
          if ! curl -s --head https://studaki.com | grep "200 OK" > /dev/null; then
            echo "Server is not running!"
            exit 1
          else
            echo "Server is running successfully."
          fi